export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const ADD_ACTIVE_USER = 'ADD_ACTIVE_USER';
export const REMOVE_ACTIVE_USER = 'REMOVE_ACTIVE_USER';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';